- hosts: all

  vars:
    - user: usuario
    - sqlserver_instance: localhost
    - sqlserver_username: sa
    - sqlserver_password: pass
    - database_name: dbname
    - database_table: tablename

  tasks:
    - name: Identify Statistics
      win_command: sqlcmd -S {{ sqlserver_instance }} -U {{ sqlserver_username }} -P {{ sqlserver_password }} -q "USE [{{ database_name }}]; SELECT [sp].[stats_id], [stat].[name], [stat].[filter_definition], [sp].[last_updated], [sp].[rows], [sp].[rows_sampled], [sp].[steps], [sp].[unfiltered_rows], [sp].[modification_counter], OBJECT_NAME([stat].[object_id]) AS [object_name], [stat].[object_id] FROM [sys].[stats] AS [stat] CROSS APPLY [sys].[dm_db_stats_properties]([stat].[object_id], [stat].[stats_id]) AS [sp] WHERE [stat].[object_id]=OBJECT_ID('{{ database_table }}');"
      register: result_valid
    - debug: var=result_valid.stdout_lines

    - name: Update Statistics
      win_command: sqlcmd -S {{ sqlserver_instance }} -U {{ sqlserver_username }} -P {{ sqlserver_password }} -q "USE [{{ database_name }}]; UPDATE STATISTICS {{ database_table }};"
      register: result_valid
    - debug: var=result_valid.stdout_lines
