- hosts: localhost
  
  vars:
    - oracle_host: '192.168.11.2'
    - oracle_port: '1521'
    - oracle_sid: 'noctopus11'
    - oracle_user: 'marco'
    - oracle_password: 'Temporal1'

  gather_facts: true

  environment:
    LD_LIBRARY_PATH: /opt/oracle/instantclient_12_2
   
  tasks:
  
 ########################################################################################################
    
    - name: Total de Objetos Invalidos
      orclqry:
        host: '{{ oracle_host }}'
        port: '{{ oracle_port }}'
        sid: '{{ oracle_sid }}'
        user: '{{ oracle_user }}'
        password: '{{ oracle_password }}'
        query: "SELECT COUNT(1) as NumObjetosInvalid
                FROM DBA_OBJECTS
                WHERE STATUS != 'VALID'"
      register: reg_Query01
      delegate_to: localhost

    - set_fact: rs_Json01="{{ reg_Query01.message |from_json}}"
      when: reg_Query01.changed
      
    - debug:
        msg: "NUMOBJETOSINVALID: {{item.NUMOBJETOSINVALID}} " 
      with_items: "{{ rs_Json01 }}" 

 ########################################################################################################

   
    - name: Lista los Objetos Invalidos
      orclqry:
        host: '{{ oracle_host }}'
        port: '{{ oracle_port }}'
        sid: '{{ oracle_sid }}'
        user: '{{ oracle_user }}'
        password: '{{ oracle_password }}'
        query: "SELECT  owner as Owner,
                        object_type as TipoObjeto,
                        object_name as NombreObjeto,
                        status as Estado
                FROM   dba_objects
                WHERE  status = 'INVALID'
                ORDER BY owner, object_type, object_name"
      register: reg_Query02
      delegate_to: localhost

    - set_fact: rs_Json02="{{ reg_Query02.message |from_json}}"
      when: reg_Query02.changed
      
    - debug:
        msg: "OWNER: {{item.OWNER}} TIPOOBJETO: {{item.TIPOOBJETO}} NOMBREOBJETO: {{item.NOMBREOBJETO}} ESTADO: {{item.ESTADO}} " 
      with_items: "{{ rs_Json02 }}" 

 ########################################################################################################
   
    - name: Compila los Objetos Invalidos
      orclqry:
        host: '{{ oracle_host }}'
        port: '{{ oracle_port }}'
        sid: '{{ oracle_sid }}'
        user: '{{ oracle_user }}'
        password: '{{ oracle_password }}'
        query: "SELECT  OWNER,
                        OBJECT_TYPE as TipodeObjeto,
                        OBJECT_NAME as NombreObjeto,
                        LAST_DDL_TIME as LastDDLTime,
                        DECODE( OBJECT_TYPE, 'PACKAGE BODY','ALTER PACKAGE '||OWNER||'.'||OBJECT_NAME||' COMPILE BODY;','ALTER '||OBJECT_TYPE||' '||OWNER||'.'||OBJECT_NAME||' COMPILE;') COMPILAR
                FROM DBA_OBJECTS
                WHERE STATUS != 'VALID'
                ORDER BY LAST_DDL_TIME"
      register: reg_Query03
      delegate_to: localhost

    - set_fact: rs_Json03="{{ reg_Query03.message |from_json}}"
      when: reg_Query03.changed
      
    - debug:
        msg: "OWNER: {{item.OWNER}} TIPODEOBJETO: {{item.TIPODEOBJETO}} NOMBREOBJETO: {{item.NOMBREOBJETO}} LASTDDLTIME: {{item.LASTDDLTIME}} COMPILAR: {{item.COMPILAR}} " 
      with_items: "{{ rs_Json03 }}" 

 ########################################################################################################