---
- hosts: ntpocrh8005
  tasks:
  
  - name: Revisa el File System
    ansible.builtin.wait_for:
        timeout: 70
    delegate_to: localhost
  
  - name: Depura File system
    ansible.builtin.file:
      path: /ansible/temporal
      state: absent
    register: result_valid
  - debug: var=result_valid.stdout_lines
  
  - name: Crea el directorio Temporal
    ansible.builtin.file:
    path: /ansible/temporal
    state: directory
    mode: '0755'