- hosts: all

  vars:
    user: usuario

  tasks:
    - name: Add user to sudoers file system
      become: true
      become_user: root
      ansible.builtin.lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^{{ user }} ALL=(ALL) NOPASSWD:ALL'
        line: '{{ user }} ALL=(ALL) NOPASSWD:ALL'
        validate: /usr/sbin/visudo -cf %s
