- hosts: all

  vars:
    - repo:
        Debian:
        - apt
        RedHat:
        - epel-release
    - distribution: debian
    - packages: docker.io
    - validatecmd: demo --version

  tasks:
    - name: Install App Repository
      become: true
      package:
        name: "{{ repo[ansible_os_family] }}"

    - name: Uninstall Package
      become: true
      package:
        name: "{{ packages }}"
        state: absent
      when: ansible_facts['os_family'] == distribution

    - name: Check package installation
      become: true
      command: "{{ validatecmd }}"
      register: result_valid
      ignore_errors: yes
    # - debug: var=result_valid.stdout_lines
      when: ansible_facts['os_family'] == distribution

    - name: Message Result
      become: true
      debug: 
        msg: "No se encontro el paquete instalado"
      when: result_valid.stdout.find('version') == -1
